//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ligg.EasyWinApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EasyWinAppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EasyWinAppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ligg.EasyWinApp.Resources.EasyWinAppRes", typeof(EasyWinAppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Option.
        /// </summary>
        public static string AccountOption {
            get {
                return ResourceManager.GetString("AccountOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Running Error.
        /// </summary>
        public static string ApplicationRunningError {
            get {
                return ResourceManager.GetString("ApplicationRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Start Error.
        /// </summary>
        public static string ApplicationStartError {
            get {
                return ResourceManager.GetString("ApplicationStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Account.
        /// </summary>
        public static string DomainAccount {
            get {
                return ResourceManager.GetString("DomainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logining.
        /// </summary>
        public static string Logining {
            get {
                return ResourceManager.GetString("Logining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogonFailed.
        /// </summary>
        public static string LogonFailed {
            get {
                return ResourceManager.GetString("LogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Password.
        /// </summary>
        public static string PlsInputPassword {
            get {
                return ResourceManager.GetString("PlsInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Account.
        /// </summary>
        public static string SystemAccount {
            get {
                return ResourceManager.GetString("SystemAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string UserLogon {
            get {
                return ResourceManager.GetString("UserLogon", resourceCulture);
            }
        }
    }
}
