//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ligg.RpaDesk.Parser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ligg.RpaDesk.Parser.Resources.ValidationRes", typeof(ValidationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory  does not exist.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is incorrect  email adress format.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name format isincorrect! File name can only be composited by  alpha-numeric characters and - ..
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path does not exist.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not correct.
        /// </summary>
        public static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not IP format.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not  IP or mask format.
        /// </summary>
        public static string IpOrMask {
            get {
                return ResourceManager.GetString("IpOrMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is mandatory.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not mask format.
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input should be numeral.
        /// </summary>
        public static string Numeral {
            get {
                return ResourceManager.GetString("Numeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value should be between {0} to {1}.
        /// </summary>
        public static string NumeralRange {
            get {
                return ResourceManager.GetString("NumeralRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Format Is Incorrect! Password must be composited by following types: alpha, numeric characters and special characters（ !,@,#,$,%,* ,etc）, and can&apos;t be less than 7 chars.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Format Is Incorrect! Password must be composited by  2 of following types: alpha, numeric characters and special characters（ !,@,#,$,%,* ,etc）, and can&apos;t be less than 7 chars.
        /// </summary>
        public static string Password1 {
            get {
                return ResourceManager.GetString("Password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input should be an plus integer.
        /// </summary>
        public static string PlusInteger {
            get {
                return ResourceManager.GetString("PlusInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input should be an plus integer or zero.
        /// </summary>
        public static string PlusIntegerOrZero {
            get {
                return ResourceManager.GetString("PlusIntegerOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Mismatchs Regex expression.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input chars should between {0}-{1}.
        /// </summary>
        public static string StringLengthRange {
            get {
                return ResourceManager.GetString("StringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string can&apos;t exceed {0} chars.
        /// </summary>
        public static string StringMaxLength {
            get {
                return ResourceManager.GetString("StringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string can&apos;t be less than {0} chars.
        /// </summary>
        public static string StringMinLength {
            get {
                return ResourceManager.GetString("StringMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters, . or - are allowed.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is incorrect  Url format.
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
    }
}
