//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ligg.RpaDesk.WinForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ligg.RpaDesk.WinForm.Resources.ValidationRes", typeof(ValidationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t be earlier than &apos;{0}&apos;.
        /// </summary>
        public static string CanNotBeEarlierThan {
            get {
                return ResourceManager.GetString("CanNotBeEarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t be future time.
        /// </summary>
        public static string CanNotBeFutureTime {
            get {
                return ResourceManager.GetString("CanNotBeFutureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t be later than &apos;{0}&apos;.
        /// </summary>
        public static string CanNotBeLaterThan {
            get {
                return ResourceManager.GetString("CanNotBeLaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t be a null value.
        /// </summary>
        public static string CanNotBeNull {
            get {
                return ResourceManager.GetString("CanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t be past time.
        /// </summary>
        public static string CanNotBePastTime {
            get {
                return ResourceManager.GetString("CanNotBePastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Is incorrect  Email Format.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Is mandatory.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Password Format Is Incorrect! Password must be composited by following types: alpha, numeric characters and special characters（ !,@,#,$,%,* ,etc）, and can&apos;t be less than 7 chars.
        /// </summary>
        public static string PasswordFormat {
            get {
                return ResourceManager.GetString("PasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Should Be Between  &apos;{0}&apos;  And &apos;{1}&apos;.
        /// </summary>
        public static string ShouldBeBetween {
            get {
                return ResourceManager.GetString("ShouldBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Input string can&apos;t exceed {0} chars.
        /// </summary>
        public static string StringMaxLength {
            get {
                return ResourceManager.GetString("StringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Input string can&apos;t be less than {0} chars.
        /// </summary>
        public static string StringMinLength {
            get {
                return ResourceManager.GetString("StringMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Is Incorrect  Url Format.
        /// </summary>
        public static string WebUrlFormat {
            get {
                return ResourceManager.GetString("WebUrlFormat", resourceCulture);
            }
        }
    }
}
