//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ligg.WinForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinformRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinformRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ligg.WinForm.Resources.WinformRes", typeof(WinformRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Application Running Error.
        /// </summary>
        public static string ApplicationRunningError {
            get {
                return ResourceManager.GetString("ApplicationRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Canceled.
        /// </summary>
        public static string BackgroundTaskStatus_Canceled {
            get {
                return ResourceManager.GetString("BackgroundTaskStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Completed.
        /// </summary>
        public static string BackgroundTaskStatus_Completed {
            get {
                return ResourceManager.GetString("BackgroundTaskStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Failed.
        /// </summary>
        public static string BackgroundTaskStatus_Failed {
            get {
                return ResourceManager.GetString("BackgroundTaskStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Processing....
        /// </summary>
        public static string BackgroundTaskStatus_Processing {
            get {
                return ResourceManager.GetString("BackgroundTaskStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Waiting....
        /// </summary>
        public static string BackgroundTaskStatus_Waiting {
            get {
                return ResourceManager.GetString("BackgroundTaskStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Choose language.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cycle Time.
        /// </summary>
        public static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dispensing.
        /// </summary>
        public static string Dispensing {
            get {
                return ResourceManager.GetString("Dispensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Error Message.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Export To Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Find Out.
        /// </summary>
        public static string FindOut {
            get {
                return ResourceManager.GetString("FindOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Finish Time.
        /// </summary>
        public static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  First.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  First Run Time.
        /// </summary>
        public static string FirstRunTime {
            get {
                return ResourceManager.GetString("FirstRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Go To.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hide Left Division.
        /// </summary>
        public static string HideLeftDivision {
            get {
                return ResourceManager.GetString("HideLeftDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Init Data.
        /// </summary>
        public static string InitData {
            get {
                return ResourceManager.GetString("InitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Last.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Latest Start Time.
        /// </summary>
        public static string LatestStartTime {
            get {
                return ResourceManager.GetString("LatestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MilliSeconds.
        /// </summary>
        public static string MilliSeconds {
            get {
                return ResourceManager.GetString("MilliSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Next.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Open Text File.
        /// </summary>
        public static string OpenTextFile {
            get {
                return ResourceManager.GetString("OpenTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please Wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Pls Input Date&amp;Time.
        /// </summary>
        public static string PlsInputDateTime {
            get {
                return ResourceManager.GetString("PlsInputDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pls Input Text.
        /// </summary>
        public static string plsInputText {
            get {
                return ResourceManager.GetString("plsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Prev.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Record Count.
        /// </summary>
        public static string RecordCount {
            get {
                return ResourceManager.GetString("RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Restore Original Content.
        /// </summary>
        public static string RestoreOriginalContent {
            get {
                return ResourceManager.GetString("RestoreOriginalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Rich Text Editor.
        /// </summary>
        public static string RichTextViewer {
            get {
                return ResourceManager.GetString("RichTextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Running Log.
        /// </summary>
        public static string RunningLog {
            get {
                return ResourceManager.GetString("RunningLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Send Error Info. To Developer.
        /// </summary>
        public static string SendErrorInfoToDev {
            get {
                return ResourceManager.GetString("SendErrorInfoToDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Set Value.
        /// </summary>
        public static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Show Left Division.
        /// </summary>
        public static string ShowLeftDivision {
            get {
                return ResourceManager.GetString("ShowLeftDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Show Log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sort By Ascending.
        /// </summary>
        public static string SortByAscending {
            get {
                return ResourceManager.GetString("SortByAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sort By Descending.
        /// </summary>
        public static string SortByDescending {
            get {
                return ResourceManager.GetString("SortByDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  System Message.
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Task List.
        /// </summary>
        public static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Time Left.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  VerificationParams have Problem, pls check!.
        /// </summary>
        public static string VerificationParamsHaveProblem {
            get {
                return ResourceManager.GetString("VerificationParamsHaveProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zoom In.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zoom Out.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
